/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muskaan.s.dbms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author muskaan
 */
public class donate_now extends javax.swing.JFrame {

    /**
     * Creates new form donate_now
     */
    public donate_now(int dID) {
        initComponents();
        this.setSize(822,450);
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        t3.setText(String.valueOf(dID));
        t3.setEditable(false);
        bloodgroup_label.setText(null);
        bloodgroup_label.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        bloodgroup_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("No. of Units:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 130, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 180, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muskaan/s/dbms/img_6ca4b0d88b7e408d4043120b392c82b1_1517214495395_original.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Donate.!");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 100, 40));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Make A Donation.!");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Camp donated in:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 180, -1));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 180, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Donor ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 130, -1));
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 180, -1));

        bloodgroup_label.setText("jLabel6");
        getContentPane().add(bloodgroup_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
boolean supress_code=false;
boolean supress_av=false;
boolean supress_rem=false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int new_val=0;
String url = "jdbc:sqlite:C:\\Users\\HP\\Desktop\\Muskaan\\Notes\\Year 2\\Sem 4\\DBMS\\project\\bloodbank.db";
Connection conn = null;
try {
    conn = DriverManager.getConnection(url);
    }
catch (SQLException e) {
    System.out.println(e.getMessage());
    }
int dID=Integer.parseInt(t3.getText());
String camp_name=t2.getText();
int units=Integer.parseInt(t1.getText());
//start
String sql_rem="Select * from donor_rem;";
try
{
    Statement stmt_check=conn.createStatement();
    ResultSet rs_check= stmt_check.executeQuery(sql_rem);
    while(rs_check.next())
    {
        if(rs_check.getInt("DonorID")==dID)
        {
            supress_rem=true;
            break;
        }
    }
}
catch(SQLException e)
{
    System.out.println(e.getMessage());
}
if(supress_rem==false){
String sql_rem2="INSERT INTO donor_rem VALUES("+dID+","+units+");";
        try
        {
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(sql_rem2);
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }  
}
else
{
    String sql_update="Select * from donor_rem where DonorID="+dID+";";
    try
    {
        Statement stmt_update=conn.createStatement();
        ResultSet rs_update=stmt_update.executeQuery(sql_update);
        new_val=rs_update.getInt("Units_left")+Integer.parseInt(t1.getText());
        String sql="Update donor_rem set Units_left="+new_val+" where DonorID="+dID+";";
        stmt_update.executeUpdate(sql);
    }
    catch(SQLException e)
    {
        System.out.println(e.getMessage());
    }
}
//dont change anything idhar se
String retrieve_bloodg="SELECT Blood_Group from donor where DonorID="+dID+";";
try{
    Statement stmt_bg=conn.createStatement();
    ResultSet rs_bg= stmt_bg.executeQuery(retrieve_bloodg);
    bloodgroup_label.setText(rs_bg.getString("Blood_Group"));
}
catch(SQLException e)
{
    System.out.println(e.getMessage());
}
String sql_check="Select * from donation;";
try
{
    Statement stmt_check=conn.createStatement();
    ResultSet rs_check= stmt_check.executeQuery(sql_check);
    while(rs_check.next())
    {
        if(rs_check.getInt("DonorID")==dID)
        {
            supress_code=true;
            break;
        }
    }
}
catch(SQLException e)
{
    System.out.println(e.getMessage());
}
if(supress_code==false){
String sql="INSERT INTO donation VALUES("+dID+",'"+units+"','"+camp_name+"');";
        try
        {
            Statement stmt=conn.createStatement();
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Thank you for donating!");
            conn.close();
            this.dispose();
            new F1().setVisible(true);
        }
        catch (SQLException e)
        {
            System.out.println(e.getMessage());
        }  
}
else
{
    String sql_update="Select * from donation where DonorID="+dID+";";
    try
    {
        Statement stmt_update=conn.createStatement();
        ResultSet rs_update=stmt_update.executeQuery(sql_update);
        new_val=rs_update.getInt("Units")+Integer.parseInt(t1.getText());
        String sql="Update donation set units="+new_val+",camp='"+t2.getText()+"' where DonorID="+dID+";";
        stmt_update.executeUpdate(sql);
        conn.close();
        this.dispose();
        new F1().setVisible(true);
    }
    catch(SQLException e)
    {
        System.out.println(e.getMessage());
    }
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(donate_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(donate_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(donate_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(donate_now.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            int dID=0;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new donate_now(dID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bloodgroup_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    // End of variables declaration//GEN-END:variables
}
